---
  - name: Cluster ID
    shell: oc get clusterversion -o jsonpath='{.items[].spec.clusterID}'
    ignore_errors: true
    register: cluster_id
    changed_when: false
  
  - name: Cluster Version
    shell: oc get clusterversion/version -o jsonpath='{.status.desired.version}'
    ignore_errors: true
    register: cluster_version
    changed_when: false

  - name: Set the fact  variable names
    set_fact: 
      cluster_id: "{{ cluster_id.stdout_lines }}"
      cluster_version: "{{ cluster_version.stdout_lines }}"
  
  

