---
- name: Info for internal OCP components.
  hosts: localhost
  gather_facts: false
  vars_files:
    - ["./settings/configs.yml"]
    - ["./settings/comments.yml"]
  roles:
    - podinfo
    - clusterinfo
    - nodeinfo
#    - certificates
    - etcd
    - csr
    - machineconfigpools
#    - kubelets
    - networks
    - operators
    - alerts
    - storage
    - resourcequotas
    - imageregistry
   

    


      



