---
- name: Generate the OpenShift Health Check Report.
  hosts: localhost
  gather_facts: false
  vars_files:
    - ["./settings/configs.yml"]

  tasks:
#    - name: Generate the OpenShift Health Check Report in .txt format
#      ansible.builtin.template:
#        src: ./templates/OpenShift_hc_report.j2
#        dest: openshift_hc_report_{{ ansible_hostname }}.txt

    - name: Generate the OpenShift Health Check Report in .adoc format
      ansible.builtin.template:
        src: ./templates/openshift_hc_report.adoc
        dest: openshift_hc_report_demo.adoc
    
    - name: Ansible delete file glob
      find:
        paths: '.'
        patterns: "*.pdf"
      register: file_to_delete

    - name: Remove pdf file if present
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ file_to_delete.files }}"
    
    - name: Generate the PDF file
      ansible.builtin.shell: |
          export CUSTOMERNAME={{ CUSTOMERNAME }}
          export DATEFORMAT={{ DATEFORMAT }}
          sh generate-pdf -f openshift_hc_report_demo.adoc --adoc
      
