---
- name: Generate the OpenShift Health Check Report.
  hosts: localhost
  gather_facts: false
  tasks:
#    - name: Generate the OpenShift Health Check Report in .txt format
#      ansible.builtin.template:
#        src: ./templates/OpenShift_hc_report.j2
#        dest: openshift_hc_report_{{ ansible_hostname }}.txt

    - name: Generate the OpenShift Health Check Report in .adoc format
      ansible.builtin.template:
        src: ./templates/openshift_hc_report.adoc
        dest: openshift_hc_report_demo.adoc
    
    - name: Ansible delete file glob
      find:
        paths: //Users/asikder/Desktop/GitOps/health-check/automated_openshift_health_check
        patterns: "*.pdf"
      register: file_to_delete

    - name: Remove pdf file if present
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ file_to_delete.files }}"
    
    - name: Identify free disk space on all mounted filesystems
      ansible.builtin.shell: sh generate-pdf -f openshift_hc_report_demo.adoc --adoc