---
- name: Generate the OpenShift Health Check Report.
  hosts: localhost
  gather_facts: false
  vars:
    customer_name: "{{ CUSTOMERNAME | replace(' ','_') }}"
  roles:
    #- etcd 
    - podinfo
    - clusterinfo
    - nodeinfo
    - certificates
    - csr
    - machineconfigpools
    - kubelets
    - networks
    - operators
    - alerts
    - storage
    - resourcequotas
    - imageregistry
    - poddisruptionbudgets
  pre_tasks:
    - name: Set variables
      ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
      vars:
        params:
          files:
            - "{{ item }}"
          paths:
            - 'settings'
            - 'defaults'
      loop:
        - "configs.yml"
        - "comments.yml"
        - "recommendations.yml"
    - name: Get current ocp token
      shell: oc whoami -t
      register: token_stdout
    - name: Set token var
      set_fact:
        ocp_token: "{{ token_stdout.stdout }}"
  tasks:
    - name: Generate the OpenShift Health Check Report in .adoc format
      ansible.builtin.template:
        src: ./templates/openshift_hc_report.adoc
        dest: "{{ output_dir }}/openshift_hc_report_demo.adoc"
    - name: Ansible delete file glob # comment lines 19 to 29 out if you don't want to automatically delete healthcheck files in current directory. 
      find:
        paths: '.'
        patterns: "*.pdf"
      register: file_to_delete
    - name: Remove pdf file if present
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ file_to_delete.files }}"
    - name: Generate the PDF file
      ansible.builtin.shell: |
        TIME=$(date {{ DATEFORMAT }})
        asciidoctor-pdf -a lang=en_US --verbose --failure-level=WARN --out-file "healthcheck-{{ customer_name }}-$TIME.pdf" --attribute=versiondate=$TIME --destination-dir {{ output_dir }} --base-dir . {{ output_dir }}/openshift_hc_report_demo.adoc
