:pdf-theme: ./styles/pdf/redhat-theme.yml
:pdf-fontsdir: ./fonts
include::vars/document-vars.adoc[]

= Red Hat OpenShift Health Check Report

This is done by RH Canberra Services. 

This is a health check report for Red Hat OpenShift cluster version 4.12.39.

== Cluster Overview

=== Cluster Information:
----
Details:
Cluster API address: https://api.cluster-fsdfd.fsdfd.sandbox1213.opentlc.com:6443
Cluster ID: 4d87165f-af67-473b-8cbc-ffb668d640ff
OpenShift Cluster Version: 4.12.39
Update channel: stable-4.12
Update Available: 
OpenShift Installation method: openshift-install
OpenShift DNS Name: cluster-fsdfd.fsdfd.sandbox1213.opentlc.com
Openshift Network Type: OVNKubernetes 
Platform: 

Cluster Stats:
Number of namespaces: 67
Number of builds: 0
Number of secrets: 944
Number of config maps: 582
Number of services: 86
Number of build configs: 0
Number of custom resource definitions (CRD): 111
----

=== Nodes Information:
==== Nodes: 
----
 
----
==== Nodes that are in 'Not Ready' state:
----

---- 

=== Pods Information:
==== Pods Not Running
----
- This check looks into the number of pods across the cluster that are not running
    successfully.
- 'Result: All pods are in Running state, no errors as of now.'

----
==== Pods Restarted
----
- This check looks into the number of pods that have restarted after for 6 times or
    more.
- 'Result: None of the pods have restarted.'

----

*Observation:*

==== CSR:
----
- ['pending csrs', '0']
----

=== *MachineConfig Information*:

The following check gets the names of machine config pools and other relevant information for a consultant's discretion. 
----
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master   rendered-master-16c5cf7344b8cb4da3c43a121929c59e   True      False      False      1              1                   1                     0                      33m
worker   rendered-worker-3656992370e799a1a07a43806cfba3a7   True      False      False      3              3                   3                     0                      33m
----
The following breaks down which nodes are associated into which machine config pool.
----
NAME                                         STATUS   ROLES                  AGE   VERSION
ip-10-0-185-183.us-east-2.compute.internal   Ready    control-plane,master   35m   v1.25.14+20cda61
ip-10-0-202-30.us-east-2.compute.internal    Ready    worker                 23m   v1.25.14+20cda61
ip-10-0-211-189.us-east-2.compute.internal   Ready    worker                 18m   v1.25.14+20cda61
ip-10-0-248-72.us-east-2.compute.internal    Ready    worker                 23m   v1.25.14+20cda61
----
Degraded machine counts refer to the number of machines in your OCP cluster that are experiencing issues or are in a degraded state. This would affect application availability and resource utilisation. (Preferred State is zero)
----
Degraded MCPs Status: This check looks into the degraded MachineConfigPools.
Result: No counts of degraded mcps.
----
Nodes may be in a pending state that may eventuate to the degraded state, whilst the OCP Health Check is occurring. The prefferred state is each Machine Config Pool having a 0 value. (Read the following as first mcp's unavailable value is the first character of the string and so on)
----
unavailable_nodes_count: "00"
----


=== *Resource Quotas*:
----
Name: 
['host-network-namespace-quotas']

Hard Limit:
['{"count/daemonsets.apps":"0","count/deployments.apps":"0","limits.cpu":"0","limits.memory":"0","pods":"0"}']

Used Limit:
['{"count/daemonsets.apps":"0","count/deployments.apps":"0","limits.cpu":"0","limits.memory":"0","pods":"0"}']
----
=== *Image Registry*:

The Management State of the Image Registry Operator alters the behaviour of the deployed image pruner job. 
 * 'Managed' means the --prune-registry flage for image pruner is set to true (preferred state).
 * 'Removed' means the --prune-registry flag for the image pruner is set to false, meaning it only prunes image metadata in etcd.
 * 'Unmanaged' means the --prune-registry flag for the image pruner is set to false. 
----
The Management State of Image Registry Operator: Managed
----

Builder images are base images that contain the necessary tools and runtime for building and compiling source code into executable applications. Builder images are used as a foundation for creating applicating  images. They are often provided by Openshift, the community, or can be custom-built to suit specific development environments and languages. 

This check is assuming the images are in the openshift-image-registry namespace and/or master nodes. 

The check has found the following images that is not provided by releases of Red Hat and OpenShift. Please review the health of these images through Red Hat Advanced Cluster Security and/or through organisational policies. 
----
docker.io/acmephp/acmephp                 latest      5737c8b963f0  4 years ago    94.4 MB
quay.io/openshifttest/hello-openshift     winc-1.2.0  74fc2eabacfe  17 months ago  54.6 MB

----

=== Operators 
==== List of Cluster Service Versions that have not Succeeded:
----

----
==== List of install plans that have not been approved: 
----

----
==== List of operators: 
----

----

=== Networks 
==== List of routes that have not been admitted:
----

----

=== Persistent Storage

Persistent storage in OpenShift uses the Kubernetes persistent volume (PV) framework that allows cluster administrators to provision persistent storage for a cluster. Developers use persistent volume claims (PVCs) to request PV resources without having specific knowledge of the underlying storage infrastructure.  PVCs are specific to a project while PV resources on their own are not scoped to any single project. After a PV is bound to a PVC, that PV can not then be bound to additional PVCs.  PVCs can exist in the system that are not owned by any container. This may be intentional, if the PVC is to be retained for future use.

==== Storage Classes

StorageClass objects describes and classifies storage that can be requested and serve as a management mechanism for controlling different levels of storage and access to that storage.  

The following storage classes are defined in the cluster:

[cols="1,1"]
|===
|**Name**
|gp2-csi

|**Provisioner**
|ebs.csi.aws.com

|**Default**
| 

|===
[cols="1,1"]
|===
|**Name**
|gp3-csi

|**Provisioner**
|ebs.csi.aws.com

|**Default**
| true

|===

==== Bound PersistentVolumeClaims

The following list of PersistentVolumeClaims (PVC) are defined and bound to an underlying Persistent Volume (PV) in the cluster across all namespaces:




