:pdf-theme: ./styles/pdf/redhat-theme.yml
:pdf-fontsdir: ./fonts
include::vars/document-vars.adoc[]

= Red Hat OpenShift Health Check Report

== Disclaimer

_This health check provides a best effort evaluation of the targeted OCP cluster(s). The results from the
report do not in any way provide a guarantee or warranty for the health and performance of the targeted
OCP cluster(s). The health check aims to provide an indication of overall health and provide consultant
recommendations on a best effort basis._

The OC cli version of the bash: 
----
OpenShift `oc` CLI Client Version:  4.13.8
OpenShift Cluster (Server) Version: 4.14.1
----

== Cluster Overview
Details of the OpenShift cluster are listed below. These are informations to reflect the cluster version and type. 

=== Cluster Information:
----
Details:
Cluster API address: https://api.ft-infra.gpslab.cbr.redhat.com:6443
Cluster ID: abb430a7-8193-4b37-a43e-ee6a42b3d75d
OpenShift Cluster Version: 4.14.1
Update channel: stable-4.14
Update Available: 
OpenShift Installation method: 
OpenShift DNS Name: ft-infra.gpslab.cbr.redhat.com
Openshift Network Type: OVNKubernetes 

Cluster Stats:
Number of namespaces: 69
Number of builds: 0
Number of secrets: 938
Number of config maps: 500
Number of services: 87
Number of build configs: 0
Number of custom resource definitions (CRD): 119
----

=== Nodes Information:
This section shows information of all the nodes present in the cluster, and lists their status, role, Operating System and their versions and when the nodes were created. 


==== Nodes: 
----
{
  "NAME": "lab-master-1",
  "READY": "True",
  "ROLE": "control-plane,master,worker",
  "CREATED_ON": "2023-11-10T06:01:00Z",
  "VERSION": "v1.27.6+f67aeb3",
  "OS": "Red Hat Enterprise Linux CoreOS 414.92.202310270216-0 (Plow)"
}
{
  "NAME": "lab-master-2",
  "READY": "True",
  "ROLE": "control-plane,master,worker",
  "CREATED_ON": "2023-11-10T05:28:41Z",
  "VERSION": "v1.27.6+f67aeb3",
  "OS": "Red Hat Enterprise Linux CoreOS 414.92.202310270216-0 (Plow)"
}
{
  "NAME": "lab-master-3",
  "READY": "True",
  "ROLE": "control-plane,master,worker",
  "CREATED_ON": "2023-11-10T05:27:19Z",
  "VERSION": "v1.27.6+f67aeb3",
  "OS": "Red Hat Enterprise Linux CoreOS 414.92.202310270216-0 (Plow)"
} 
----
==== Nodes that are in 'Not Ready' state:
This health check looks into the statuses of each nodes and lists if there are any non-working nodes. A blank section reflects all the nodes are in a working successfully. 

----

---- 

=== Pods Information:
Pods are critical to how OpenShift runs its operations and applications. This section checks into their status and returns observations of non-working pods. 

==== Pods Not Running
The number of pods not running shows which pods in the entire OCP cluster is not running. If there are none, the logical implementation of the check returns a message reflecting the status. 

----
- This check looks into the number of pods across the cluster that are not running
    successfully.
- 'The number of pods not running are:  5'
- pod/installer-3-lab-master-2
- pod/installer-4-lab-master-2
- pod/installer-4-lab-master-3
- pod/installer-5-lab-master-3
- pod/installer-4-lab-master-2

----
==== Pods Restarted
Pods that have containers which have restarted for more than a `threshold` is pointed out and observed in this health check, and the the logical implementation also returns a no error message if there no pods with that threshold amount of container restarts. 

----
- This check looks into the number of pods that have restarted after for 6 times or
    more.
- 'The number of pods restarted 6 times or more are:  1'
- This check has produced the following errors.
- --
- 'Name of Pod: openshift-cloud-controller-manager-operator'
- 'Namespace: cluster-cloud-controller-manager-operator-67b6d64d65-xm8w4'
- 'Restarts: 6'
- --

----

*Observation:*

==== CSR:
----
- ['pending csrs', '0']
----

=== *MachineConfig Information*:

The following check gets the names of machine config pools and other relevant information for a consultant's discretion. 
----
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master   rendered-master-6072a94891bc4c5e3461cea3cb245a54   True      False      False      3              3                   3                     0                      63m
worker   rendered-worker-d47a80773212e66f1bfc6ca577067555   True      False      False      0              0                   0                     0                      63m
----
The following breaks down which nodes are associated into which machine config pool.
----
NAME           STATUS   ROLES                         AGE   VERSION
lab-master-1   Ready    control-plane,master,worker   41m   v1.27.6+f67aeb3
lab-master-2   Ready    control-plane,master,worker   74m   v1.27.6+f67aeb3
lab-master-3   Ready    control-plane,master,worker   75m   v1.27.6+f67aeb3
----
Degraded machine counts refer to the number of machines in your OCP cluster that are experiencing issues or are in a degraded state. This would affect application availability and resource utilisation. (Preferred State is zero)
----
Degraded MCPs Status: This check looks into the degraded MachineConfigPools.
Result: No counts of degraded mcps.
----
Nodes may be in a pending state that may eventuate to the degraded state, whilst the OCP Health Check is occurring. The prefferred state is each Machine Config Pool having a 0 value. (Read the following as first mcp's unavailable value is the first character of the string and so on)

****
Unavailablenodes:
[.green]#['machineconfigpool.machineconfiguration.openshift.io/master', '0']#
[.green]#['machineconfigpool.machineconfiguration.openshift.io/worker', '0']#
****
****
[['machineconfigpool.machineconfiguration.openshift.io/master', '0'], ['machineconfigpool.machineconfiguration.openshift.io/worker', '0']]
****
=== *Resource Quotas*:
----
Name: 
['host-network-namespace-quotas']

Hard Limit:
['{"count/daemonsets.apps":"0","count/deployments.apps":"0","limits.cpu":"0","limits.memory":"0","pods":"0"}']

Used Limit:
['{"count/daemonsets.apps":"0","count/deployments.apps":"0","limits.cpu":"0","limits.memory":"0","pods":"0"}']
----
=== Image Registry:

The Management State of the Image Registry Operator alters the behaviour of the deployed image pruner job. 

* 'Managed' means the --prune-registry flage for image pruner is set to true (preferred state).
* 'Removed' means the --prune-registry flag for the image pruner is set to false, meaning it only prunes image metadata in etcd.
* 'Unmanaged' means the --prune-registry flag for the image pruner is set to false. 



****
Management State: [.orange]#Removed#
****


Builder images are base images that contain the necessary tools and runtime for building and compiling source code into executable applications. Builder images are used as a foundation for creating applicating  images. They are often provided by Openshift, the community, or can be custom-built to suit specific development environments and languages. 

This check is assuming the images are in the openshift-image-registry namespace and/or master nodes. 

The check has found the following images that is not provided by releases of Red Hat and OpenShift. Please review the health of these images through Red Hat Advanced Cluster Security and/or through organisational policies. 
****
External images on node: [.green]#No external images found on nodes#
****
****
External images in namespace: [.green]#No external images found on namespaces#
****

=== Operators 
==== List of Cluster Service Versions that have not Succeeded:
An empty section reflects that there are no CSV's in unsuccessful state and are all healthy. 

----

----
==== List of install plans that have not been approved: 
An empty section reflects that all the Install Plans for the Operators subscriptions have been approved. 

----

----
==== List of operators: 
----

----

=== Networks 
The network-check looks into the entire OCP cluster and observes which Ingress policies have not been admitted to a network. 


==== List of routes that have not been admitted:
An empty section reflects that all the Ingress policies in the cluster have been admitted. 

----

----

=== Persistent Storage

Persistent storage in OpenShift uses the Kubernetes persistent volume (PV) framework that allows cluster administrators to provision persistent storage for a cluster. Developers use persistent volume claims (PVCs) to request PV resources without having specific knowledge of the underlying storage infrastructure.  PVCs are specific to a project while PV resources on their own are not scoped to any single project. After a PV is bound to a PVC, that PV can not then be bound to additional PVCs.  PVCs can exist in the system that are not owned by any container. This may be intentional, if the PVC is to be retained for future use.

==== Storage Classes

StorageClass objects describes and classifies storage that can be requested and serve as a management mechanism for controlling different levels of storage and access to that storage.  

The following storage classes are defined in the cluster:


==== Bound PersistentVolumeClaims

The following list of PersistentVolumeClaims (PVC) are defined and bound to an underlying Persistent Volume (PV) in the cluster across all namespaces:





=== *Kubelets*:

==== Authentication
Anonymous authentication should be preferably set to false, in order for users to identify themselves befor authentication to API.
----
The node is lab-master-1
      "enabled": false
The node is lab-master-2
      "enabled": false
The node is lab-master-3
      "enabled": false
----
==== Pods
podsPerCore sets the number of pods the node can run based on the number of processor cores on the node.podsPerCore cannot exceed maxPods (default state of maxPods is 250 pods with 4096 podPidsLimit)
----
The node is lab-master-1
  "maxPods": 250,
  "podPidsLimit": 4096,
The node is lab-master-2
  "maxPods": 250,
  "podPidsLimit": 4096,
The node is lab-master-3
  "maxPods": 250,
  "podPidsLimit": 4096,
----
==== APIs
The rate at which the kubelet talks to the API server depends on queries per second (QPS) and burst values. The default values 50 for kubeAPIQPS and 100 for kubeAPIBurst, are good enough if there are limited pods running on each node. Updating the kubelet QPS and burst rates is recommended if there are enough CPU and memory resources on the node.
----
The node is lab-master-1
  "kubeAPIQPS": 50,
  "kubeAPIBurst": 100,
The node is lab-master-2
  "kubeAPIQPS": 50,
  "kubeAPIBurst": 100,
The node is lab-master-3
  "kubeAPIQPS": 50,
  "kubeAPIBurst": 100,
----
==== Rotate Certificates
Having rotate certificates enabled makes sure that nodes are more consistently available, whilst certificates may expire.
----
The node is lab-master-1
  "rotateCertificates": true,
The node is lab-master-2
  "rotateCertificates": true,
The node is lab-master-3
  "rotateCertificates": true,
----
==== CgroupDriver
Cgroupfs and systemd are the predominant cgroup drivers. The preferred driver is systemd as it is tightly integrated with cgroups and will assin a cgroup to each systemd unit. Using cgroupfs with systemd means that there will be two different cgroup managers( ie two views of the resources)
----
The node is lab-master-1
  "cgroupDriver": "systemd",
The node is lab-master-2
  "cgroupDriver": "systemd",
The node is lab-master-3
  "cgroupDriver": "systemd",
----
==== CgroupRoot
CgroupRoot should be roots directory. Ensuring that the kubelet service file ownership is set to root.
----
The node is lab-master-1
  "cgroupRoot": "/",
The node is lab-master-2
  "cgroupRoot": "/",
The node is lab-master-3
  "cgroupRoot": "/",
----
==== Permissions
Ensuring that the kubelet service file permissions are set to 644 or more restrictive.
----
The node is lab-master-1
-rw-r--r--. 1 root root 2906 Nov 10 06:02 /etc/kubernetes/kubelet.conf
The node is lab-master-2
-rw-r--r--. 1 root root 2906 Nov 10 05:53 /etc/kubernetes/kubelet.conf
The node is lab-master-3
-rw-r--r--. 1 root root 2906 Nov 10 05:56 /etc/kubernetes/kubelet.conf
----
==== clusterDNS
The IP address Pods are using for DNS resolution.
----
  "clusterDNS": [
    "172.30.0.10"
----


== Alerts:
Alert rules:

This table shows which alerts have been 'Active' and 'Fired'. The Alerts are a great indication, defined by rules using Prometheus Query Language (PQL) of what is potentially going wrong with the cluster. 

[cols="2,2,1,2" , options="unbreakable"]
|====
| Name | NameSpace | Severity | ActiveSince


| InsightsRecommendationActive | openshift-insights | info | 2023-11-10T05:59:36.479039556Z



| InsightsRecommendationActive | openshift-insights | info | 2023-11-10T05:59:36.479039556Z



| Watchdog | openshift-monitoring | none | 2023-11-10T05:59:08.530952165Z



| AlertmanagerReceiversNotConfigured | openshift-monitoring | warning | 2023-11-10T06:00:28.08951414Z


|====


== Grafana
Grafana is not present in the cluster. It may have been deprecated. Please check release notes. 

== Prometheus
This checks the prometheus pods running the cluster are running successfully or not. The ContainerReady section looks into the number of ready containers against the total number of cantainers in the pod. 
[cols="2,2,2" , options="unbreakable"]
|====
| Name | ContainerReady | Status


| prometheus-adapter-6bcb66cb55-t9zxb | 1/1 | Running 


| prometheus-adapter-6bcb66cb55-xh6jt | 1/1 | Running 


| prometheus-k8s-0 | 6/6 | Running 


| prometheus-k8s-1 | 6/6 | Running 


| prometheus-operator-59c99bbf7c-n75pk | 2/2 | Running 


| prometheus-operator-admission-webhook-7f9cfbddc5-m694q | 1/1 | Running 


| prometheus-operator-admission-webhook-7f9cfbddc5-tttsk | 1/1 | Running 

|====