---
- name: Get CSRs
  kubernetes.core.k8s_info:
    api_key: "{{ ocp_token }}"
    api_version: certificates.k8s.io/v1
    kind: CertificateSigningRequest
  register: csr

- name: Select pending CSRs and set fact
  set_fact:
    csr_pending: "{{ csr | community.general.json_query('resources[?status==`{}`]') | length }}"
