---  
  - name: Check for pods not running
    include_tasks: pods_not_running.yml

  - name: Check if pods have restarted
    include_tasks: pods_restarted.yml 

  - name: Set variable as node_master
    set_fact:
      pods_not_running: "{{ pods_not_running.stdout_lines }}"
      pods_restarted: "{{ pods_restarted.stdout_lines }}"
