- name: Check for pods not running
  shell: |
      HEALTH_CHECK_COMMENT="This check looks into the number of pods across the cluster that are not running successfully."
      OK_COMMENT=" All pods are in Running state, no errors as of now."
      ERROR_COMMENT="The number of pods not running are: "
      
      PODS_NOT_RUNNING=$(oc get pods -A --field-selector=status.phase!=Running,status.phase!=Succeeded --ignore-not-found=true -o name)
      PODS_NOT_RUNNING_NUMBER=$(echo "${PODS_NOT_RUNNING}" | wc -l | tr -d ' ')

      #echo "----"
      echo $HEALTH_CHECK_COMMENT
      if [[ -n ${PODS_NOT_RUNNING} ]] ; 
      then
          echo "${ERROR_COMMENT} ${PODS_NOT_RUNNING_NUMBER}"
          echo "${PODS_NOT_RUNNING}"
      else
          echo ${OK_COMMENT}
      fi
      #echo "----"
  args:
    executable: /bin/bash
  changed_when: false
  ignore_errors: true
  register: pods_not_running