---
### Variable file for controlling the health check ### 
### POD INFO ###
RESTART_THRESHOLD: 7
###       
### NODE INFO ###
### MachingeConfigPool Degradaded
DEGRADED_MACHINE_COUNT: 1 # default value: 1
