---
OC: /usr/local/bin/oc # Default location of the OpenShift CLI for cluster versions of 4.X. 
# IF unsure where to find 'oc' cli location, run command `whereis oc`
### Variable file for controlling the health check ### 
### POD INFO ###
RESTART_THRESHOLD: 6
###       
### NODE INFO ###
### MachingeConfigPool Degradaded
DEGRADED_MACHINE_COUNT: 1 # default value: 1
CUSTOMERNAME: baymax
DATEFORMAT: "+%m-%d-%Y"