---
  - name: Iterate through master nodes and store names as list - nodoc
    shell: "oc get nodes -l node-role.kubernetes.io/master='' | tail --lines=+2 | awk '{print $1}'"
    register: oc_master
    changed_when: false
  
  - name: Getting the number of Nodes
    shell: "oc get nodes --no-headers | wc -l | tr -d ' '"
    ignore_errors: true
    register: oc_number

  - name: Set variable
    set_fact:
      node_master: "{{ oc_master.stdout }}"
      node_number: "{{ oc_number.stdout }}"

