---
# tasks file for roles/clusteroverrride
- name: Gather node list for future loops
  ansible.builtin.shell: oc get nodes | awk '{print $1}'
  register: clusteroverride_node_details

- name: Gather node details for override assessment
  ansible.builtin.shell: oc describe nodes {{ item }} | grep -A4 "Resource" | tail -n 3
  loop: "{{ clusteroverride_node_details.stdout_lines[1:] }}"
  register: clusteroverride_results_gathered

- name: Create a new list to extract required data
  ansible.builtin.set_fact:
    clusteroverride_selected_data: "{{ (clusteroverride_selected_data | default([])) + make_value }}"
  vars:
   make_value: [ {
    name_node: "{{ item.item }}", 
    node_lines: "{{ item.stdout_lines }}" }
    ]
  loop: "{{ clusteroverride_results_gathered.results }}"
  loop_control:
    index_var: my_idx


- name: This loops through the calculation tasks 
  ansible.builtin.include_tasks: 
    file: calculate_usage.yml
  loop: "{{ clusteroverride_selected_data }}"
  loop_control:
    loop_var: outer_item

- name: Set Facts for adoc template loops
  ansible.builtin.set_fact:
    cluster_override_nodes: "{{ clusteroverride_node_details.stdout_lines[1:] }}"
    cluster_override_array: "{{ clusteroverride_selected_data | map(attribute='node_lines') | length }}"

- name: Display new results 
  ansible.builtin.debug:
    msg: "{{ override_set_statistics }}"
