---
# etcd performance / troubleshooting guide --> https://access.redhat.com/articles/6271341
- name: Get etcd pod name
  ansible.builtin.shell: oc get pods -n openshift-etcd -o jsonpath='{range .items[*].metadata}{""}{.name}{"\n"}{end}' | grep -v etcd-quorum-guard | grep etcd
  ignore_errors: true
  register: etcd_pods

- name: RSH to etcd pod | time
  kubernetes.core.k8s_exec:
    namespace: openshift-etcd
    pod: "{{ etcd_pods.stdout_lines[0] }}"
    command: "etcdctl endpoint health"
  register: etcd_time
  ignore_errors: true

- name: RSH to etcd pod | health table
  kubernetes.core.k8s_exec:
    namespace: openshift-etcd
    pod: "{{ etcd_pods.stdout_lines[0] }}"
    command: "etcdctl endpoint health -w table"
  register: etcd_table
  ignore_errors: true

- set_fact:
   etcd_time: "{{ etcd_time.stdout }}"

- name: Running a tailored version of fio
  ansible.builtin.shell: sh roles/etcd/tasks/etcd.sh
  register: fio_results


- name: Set variable
  set_fact:
    etcd_pods: "{{ etcd_pods.stdout }}"
    fio_results1: "{{ fio_results.stdout_lines[-2] | string }}"
    fio_results2: "{{ fio_results.stdout_lines[-1] | string }}"
    etcd_table: "{{ etcd_table.stdout | string }}"


 
    

