---
# Script follows existing RH solution, but adds calculations for days remaining on each cert.
# https://access.redhat.com/solutions/3930291
- name: Get tls secrets from ocp cluster
  kubernetes.core.k8s_info:
    api_key: "{{ ocp_token }}"
    api_version: v1
    kind: Secret
    field_selectors:
      - type=kubernetes.io/tls
  register: tls_secrets

- name: Get tls secrets from ocp cluster of type SecretTypeTLS
  kubernetes.core.k8s_info:
    api_key: "{{ ocp_token }}"
    api_version: v1
    kind: Secret
    field_selectors:
      - type=SecretTypeTLS
    namespace: openshift-config
  register: tls_secrets_st

- name: Create list of certificate information
  community.crypto.x509_certificate_info:
    content: "{{ item.data['tls.crt'] | b64decode }}"
  loop: "{{ tls_secrets.resources }}"
  register: ocp_tls_certificates

- name: simplify certs list register var
  set_fact:
    ocp_tls_certificates: "{{ ocp_tls_certificates.results }}"

- name: Count tls certificates
  debug:
    msg: "kubernetes.io/tls certificates - {{ ocp_tls_certificates | length }}"
