---
# get kubelet configuration from nodes
- name: Get kubelet configuration from master node
  ansible.builtin.shell: sh roles/kubelets/tasks/kubelet.sh > ./roles/kubelets/tasks/tmp.txt
  
# check anononymous authentication is turned off for each node
- name: Check anonymous authentication is turned off
  ansible.builtin.shell: cat ./roles/kubelets/tasks/tmp.txt | grep -w 'The node is\|enabled'
  register: anonymous_authentication

# get max number of pods and pids for each node
- name: Get max number of pods
  ansible.builtin.shell: cat ./roles/kubelets/tasks/tmp.txt | grep -w 'The node is\|maxPods\|podPidsLimit\|podsPerCore'
  register: kubelet_pods

# get kubeAPIQPS and kubeAPIBurst for each node
- name: Get kubeAPIQPS and kubeAPIBurst
  ansible.builtin.shell: cat ./roles/kubelets/tasks/tmp.txt | grep -w 'The node is\|kubeAPIQPS\|kubeAPIBurst'
  register: kubelet_APIs


# get rotate certificates value from each node
- name: Get rotate certificate
  ansible.builtin.shell: cat ./roles/kubelets/tasks/tmp.txt | grep -w 'The node is\|rotateCertificates'
  register: kubelet_rotate_certificate

# get cgroupDriver
- name: Get cgroupDriver
  ansible.builtin.shell: cat ./roles/kubelets/tasks/tmp.txt | grep -w 'The node is\|cgroupDriver'
  register: kubelet_cgroupDriver

# get cgroupRoot: /
- name: Get cgroupRoot
  ansible.builtin.shell: cat ./roles/kubelets/tasks/tmp.txt | grep -w 'The node is\|cgroupRoot'
  register: kubelet_cgroupRoot

# get permissions of kubelet conf file
- name: Get permissions of kubelet conf file
  ansible.builtin.shell: sh roles/kubelets/tasks/kubelet-octal.sh > ./roles/kubelets/tasks/tmp2.txt

# outputting permissions of kublet fonf from tmp2 text file
- name: Get permissions of kubelet conf file
  ansible.builtin.shell: cat ./roles/kubelets/tasks/tmp2.txt
  register: kubelet_permission

# get clusterDNS
- name: Get clusterDNS pods are using
  ansible.builtin.shell: cat ./roles/kubelets/tasks/tmp.txt | grep -A 1 -m 1 'clusterDNS'
  register: kubelet_clusterDNS

- name: Set variable
  set_fact:
    anonymous_authentication: "{{ anonymous_authentication.stdout }}"
    kubelet_pods: "{{ kubelet_pods.stdout }}"
    kubelet_APIs: "{{ kubelet_APIs.stdout }}"
    kubelet_rotate_certificate: "{{ kubelet_rotate_certificate.stdout }}"
    kubelet_cgroupDriver: "{{ kubelet_cgroupDriver.stdout }}"
    kubelet_cgroupRoot: "{{ kubelet_cgroupRoot.stdout }}"
    kubelet_permission: "{{ kubelet_permission.stdout}}"
    kubelet_clusterDNS: "{{ kubelet_clusterDNS.stdout }}"
