---
- name: Check CSVs without success
  shell: oc get csv -A | sort -u | grep -v Succeeded$ | tail -n +2
  ignore_errors: true
  register: csv

- name: Get all Install Plans
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: InstallPlan
  register: install_plans

- name: re-register InstallPlan fact with just resources
  set_fact:
    install_plans: "{{ install_plans.resources }}" 

# - name: Check install plans not approved
#   shell: oc get ip -A |sort -u | grep -v true$ | tail -n +2
#   ignore_errors: true
#   register: install_plan

- name: Get Installed Operators
  shell: oc get operators
  ignore_errors: true
  register: operators

# - set_fact:
#     CSV_STATUS: "{{ csv.stdout }}"
#     INSTALL_PLAN: "{{ install_plan.stdout  }}"
#     OPERATORS: "{{operators.stdout}}"
