:pdf-theme: ./styles/pdf/redhat-theme.yml
:pdf-fontsdir: ./fonts
:subject: Consulting Engagement Report
:docstatus: {{ docstatus }}

:toc:

= Red Hat OpenShift Health Check Report

:sectnums:
== *Disclaimer*

_This health check provides a best effort evaluation of the targeted OCP cluster(s). The results from the
report do not in any way provide a guarantee or warranty for the health and performance of the targeted
OCP cluster(s). The health check aims to provide an indication of overall health and provide consultant
recommendations on a best effort basis._


This health check has been conducted by {{ AUTHORNAME }} for {{ CUSTOMERNAME }}.


== *Cluster Overview*
Details of the OpenShift cluster are listed below. This information reflects the cluster version and type. 


The OC cli version of the bash: 
----
OpenShift `oc` CLI Client Version: *{{ cluster_cli_version }}*
OpenShift Cluster (Server) Version: *{{ cluster_version }}*
----

=== Cluster Information:
----
Details:
Cluster API address: {{ cluster_api }}
Cluster ID: {{ cluster_id }}
OpenShift Cluster Version: {{ cluster_version }}
Update channel: {{ cluster_update_channel }}
Update Available: {{ cluster_update }}
OpenShift Installation method: {{ cluster_installation_check }}
OpenShift DNS Name: {{cluster_dns_name }}
Openshift Network Type: {{ cluster_network_type }} 

Cluster Stats:
Number of namespaces: {{ cluster_namespaces }}
Number of builds: {{ cluster_builds }}
Number of secrets: {{ cluster_secrets }}
Number of config maps: {{ cluster_configmaps }}
Number of services: {{ cluster_services }}
Number of build configs: {{ cluster_bc }}
Number of custom resource definitions (CRD): {{ cluster_crds }}
----

=== Nodes Information:
This section shows information of all the nodes present in the cluster, and lists their status, role, Operating System and their versions and when the nodes were created. 


==== Nodes: 
----
{{ nodes }} 
----
==== Nodes that are in 'Not Ready' state:
This health check looks into the statuses of each nodes and lists if there are any non-working nodes. A blank section reflects all the nodes are in a working successfully. 

----
{{ nodes_not_ready }}
---- 

=== Pods Information:
Pods are critical to how OpenShift runs its operations and applications. This section checks into their status and returns observations of non-working pods. 

==== Pods Not Running
The number of pods not running shows which pods in the entire OCP cluster is not running. If there are none, the logical implementation of the check returns a message reflecting the status. 

----
{{ pods_not_running | to_nice_yaml }}
----
==== Pods Restarted
Pods that have containers which have restarted for more than a `threshold` is pointed out and observed in this health check, and the the logical implementation also returns a no error message if there no pods with that threshold amount of container restarts. 

----
{{ pods_restarted | to_nice_yaml }}
----

*Observation:*

== *CSR*
----
- {{ oc_csr_pending_fact }}
----

== *MachineConfig Information*:

The following check gets the names of machine config pools and other relevant information for a consultant's discretion. 
----
{{ machine_config_pools_name }}
----
The following breaks down which nodes are associated into which machine config pool.
----
{{ nodes_mcp }}
----
Degraded machine counts refer to the number of machines in your OCP cluster that are experiencing issues or are in a degraded state. This would affect application availability and resource utilisation. (Preferred State is zero)
****
Degraded MCPs Status:

{% if 'No counts of degraded mcps' in degraded_mcps %}
[.green]#{{ degraded_mcps }}#
{% else %}
[.red]#{{ degraded_mcps }}#
{% endif %}
****
Nodes may be in a pending state that may eventuate to the degraded state, whilst the OCP Health Check is occurring. The preferred state is each Machine Config Pool having a 0 value. (Read the following as first mcp's unavailable value is the first character of the string and so on)

****
Unavailablenodes:
{% for i in my_list %}
{% if '0' in i %}
[.green]#{{ i }}#
{% else %}
[.red]#{{ i }}#
{% endif %}
{% endfor %}
****
****
Check performed on following nodes: {{ my_list }}
****
== *Resource Quotas*:
----
Name: 
{{ resource_quota_name }}

Hard Limit:
{{ resource_quota_hard_limit }}

Used Limit:
{{ resource_quota_used_limit }}
----

== *Image Registry*

The Management State of the Image Registry Operator alters the behaviour of the deployed image pruner job. 

* 'Managed' means the --prune-registry flag for image pruner is set to true (preferred state).
* 'Removed' means the --prune-registry flag for the image pruner is set to false, meaning it only prunes image metadata in etcd.
* 'Unmanaged' means the --prune-registry flag for the image pruner is set to false. 



****
Management State: {{ color }}#{{ management_state_registry }}#
****


Builder images are base images that contain the necessary tools and runtime for building and compiling source code into executable applications. Builder images are used as a foundation for creating application  images. They are often provided by Openshift, the community, or can be custom-built to suit specific development environments and languages. 

This check is assuming the images are in the openshift-image-registry namespace and/or master nodes. 

The check has found the following images that is not provided by releases of Red Hat and OpenShift. Please review the health of these images through Red Hat Advanced Cluster Security and/or through organisational policies. 
****
External images on node: {{ color2 }}#{{ external_images_node }}#
****
****
External images in namespace: {{ color3 }}#{{ external_images_registry_namespace }}#
****

== *Operators*
=== List of Cluster Service Versions that have not Succeeded:
An empty section reflects that there are no CSV's in unsuccessful state and are all healthy. 

----
{{ CSV_STATUS }}
----
=== List of install plans that have not been approved: 
An empty section reflects that all the Install Plans for the Operators subscriptions have been approved. 

----
{{ INSTALL_PLAN }}
----
=== List of operators: 
----
{{ OPERATORS }}
----

== *Networks*
The network-check looks into the entire OCP cluster and observes which Ingress policies have not been admitted to a network. 


=== List of routes that have not been admitted:
An empty section reflects that all the Ingress policies in the cluster have been admitted. 

----
{{ routes_not_admitted }}
----

== *Persistent Storage*

Persistent storage in OpenShift uses the Kubernetes persistent volume (PV) framework that allows cluster administrators to provision persistent storage for a cluster. Developers use persistent volume claims (PVCs) to request PV resources without having specific knowledge of the underlying storage infrastructure.  PVCs are specific to a project while PV resources on their own are not scoped to any single project. After a PV is bound to a PVC, that PV can not then be bound to additional PVCs.  PVCs can exist in the system that are not owned by any container. This may be intentional, if the PVC is to be retained for future use.

=== Storage Classes

StorageClass objects describes and classifies storage that can be requested and serve as a management mechanism for controlling different levels of storage and access to that storage.  

The following storage classes are defined in the cluster:

{% for sc in storage_classes %}
[cols="1,1"]
|===
|**Name**
|{{ sc.name }}

|**Provisioner**
|{{ sc.provisioner }}

|**Default**
| {{ sc.default }}

|===
{% endfor %}

=== Bound PersistentVolumeClaims

The following list of PersistentVolumeClaims (PVC) are defined and bound to an underlying Persistent Volume (PV) in the cluster across all namespaces:

{% for pvc in bound_pvcs %}

[cols="1,1"]
|===
|**Name **
|{{ pvc.name }}

|**Namespace**
|{{ pvc.namespace }}

|**Storage Class**
|{{ pvc.storageclass }}

|**Capacity**
|{{ pvc.capacity }}

|**Access Modes**
|{{ pvc.accessmodes }}

|===

{% endfor %}

{% if unbound_pvcs|length > 0 %}
=== Un-Bound PVCs

The following list of PersistentVolumeClaims (PVC) are defined and are not bound to any underlying Persistent Volume (PV) in the cluster across all namespaces:

{% for pvc in unbound_pvcs %}

[cols="1,1"]
|===
|**Name **
|{{ pvc.name }}

|**Namespace**
|{{ pvc.namespace }}

|**Storage Class**
|{{ pvc.storageclass }}

|**Capacity**
|{{ pvc.capacity }}

|**Access Modes**
|{{ pvc.accessmodes }}

|===

{% endfor %}

PVCs may be unbound for multiple reasons.  For example: some storage classes will only bind a PVC to a PV when it is actually used.  This may be a desired state.  In other cases, a PVC may not be able to bind to a PV if the Storage Class can not satisfy the storage request if, for example, there is insufficient space available, or if the PVC is requesting an access mode not supported by that Storage Class.

**Consultant Recommendations**

__TODO__
{% endif %}

{% if orphaned_pvcs|length > 0 %}
=== Unowned PVCs

PVCs can exist in the system that are not owned by any container. This may be intentional if, for example, the PVC has been released by an application but it is intended to be reused by another application. Alternatively, the PVC may need to be manually deleted.

Results: 

{% for pvc in orphaned_pvcs %}
- {{ pvc }}

{% endfor %}

**Consultant Recommendations**

__TODO__
{% endif %}

{% if unowned_pvs|length > 0 %}
=== Unowned PVs

Persistent Volumes (PV) can exist in the system that are not owned by any PVC. This may be intentional if, for example, the PV delete policy is set to __Retain__ so that they can be manually deleted after the PVC is deleted.

Results: 

{% for pv in unowned_pvs %}
- {{ pv.name }}

{% endfor %}

**Consultant Recommendations**

__TODO__
{% endif %}

== *Kubelets*:
The following checks are occurring on the master nodes. 

=== Authentication
Anonymous authentication should be preferably set to false, in order for users to identify themselves before authentication to API.
****
{% if 'true' in anonymous_authentication %}
[.red]#{{ anonymous_authentication }}#
{% else %}
[.green]#{{ anonymous_authentication }}#
{% endif %}
****
=== Pods
podsPerCore sets the number of pods the node can run based on the number of processor cores on the node.podsPerCore cannot exceed maxPods (default state of maxPods is 250 pods with 4096 podPidsLimit)
****
{{ kubelet_pods}}
****
=== APIs
The rate at which the kubelet talks to the API server depends on queries per second (QPS) and burst values. The default values 50 for kubeAPIQPS and 100 for kubeAPIBurst, are good enough if there are limited pods running on each node. Updating the kubelet QPS and burst rates is recommended if there are enough CPU and memory resources on the node.
****
{{ kubelet_APIs }}
****
=== Rotate Certificates
Having rotate certificates enabled makes sure that nodes are more consistently available, whilst certificates may expire.
****
{% if 'false' in kubelet_rotate_certificate %}
[.red]#{{ kubelet_rotate_certificate }}#
{% else %}
[.green]#{{ kubelet_rotate_certificate }}#
{% endif %}
****
=== CgroupDriver
Cgroupfs and systemd are the predominant cgroup drivers. The preferred driver is systemd as it is tightly integrated with cgroups and will assign a cgroup to each systemd unit. Using cgroupfs with systemd means that there will be two different cgroup managers( ie two views of the resources)
****
{% if 'cgroupfs' in kubelet_cgroupDriver %}
[.orange]#{{ kubelet_cgroupDriver }}#
{% else %}
[.green]#{{ kubelet_cgroupDriver }}#
{% endif %}
****
=== CgroupRoot
CgroupRoot should be roots directory. Ensuring that the kubelet service file ownership is set to root.
****
{% if '"/"' in kubelet_cgroupRoot %}
[.green]#{{ kubelet_cgroupRoot }}#
{% else %}
[.red]#{{ kubelet_cgroupRoot }}#
{% endif %}
****
=== Permissions
Ensuring that the kubelet service file permissions are set to 644 or more restrictive.
----
{{ kubelet_permission }}
----
==== clusterDNS
The IP address Pods are using for DNS resolution.
----
{{ kubelet_clusterDNS }}
----

== *Alerts*

=== Alert rules:

This table shows which alerts have been 'Active' and 'Fired'. The Alerts are a great indication, defined by rules using Prometheus Query Language (PQL) of what is potentially going wrong with the cluster. 

[cols="2,2,1,2" , options="unbreakable"]
|====
| Name | NameSpace | Severity | ActiveSince

{% for i in range(alerts_firing_names.stdout_lines | length) %}

| {{ alerts_firing_names.stdout_lines[i]   }} | {{ alerts_firing_namespace.stdout_lines[i]   }} | {{ alerts_firing_severity.stdout_lines[i]  }} | {{ alerts_firing_active_at.stdout_lines[i] }}


{% endfor %}
|====


=== Grafana
{%if grafana_enabled.stdout|length > 0 %}
[.green] #Grafana is enabled in this cluster. #
{% else %}
[.orange]#Grafana is not present in the cluster. It may have been deprecated. Please check release notes.#
{% endif %}

=== Prometheus
This checks the prometheus pods running the cluster are running successfully or not. The ContainerReady section looks into the number of ready containers against the total number of containers in the pod. 
[cols="2,2,2" , options="unbreakable"]
|====
| Name | ContainerReady | Status

{% for i in range(prom_pods_name.stdout_lines | length) %}

| {{ prom_pods_name.stdout_lines[i]   }} | {{ prom_pods_container_ready.stdout_lines[i]   }} | {{ prom_pods_status.stdout_lines[i]  }} 

{% endfor %}
|====

== *Etcd*:
The etcd pods that are running
----
{{ etcd_pods }}
----
Fast disks are the most critical factor for etcd deployment performance and stability. A slow disk will increase ETCD request latency and potentially hurt cluster stability. Because etcd maintains a detailed record of its keyspace over time, it's necessary to regularly condense this history to prevent performance issues and avoid running out of storage space. Compacting the keyspace history removes information about keys that are no longer relevant before a specific revision, making the space used by these keys available for new data. The compaction process should be quick, ideally below 100ms (typically below 10ms for fast storage types like SSD/NVMe or AWS io1) for smaller clusters, but it can take up to 800ms for larger clusters (20 or more workers). Anything beyond 800ms could lead to performance problems.



This Health check is checking compaction rate and is assuming its for a large cluster and rounding off to closest integer of milliseconds.
****
{% if (etcd_time | split(' ') | last | split ('ms') | first | int) < 800 %}
Compaction Rate:   [.green]#{{ etcd_time | split(' ') | last | split ('ms') | first | int }} milliseconds#
{% elif 800 < (etcd_time | split(' ') | last | split ('ms') | first | int) < 900 %}
Compaction Rate:  [.orange]#{{ etcd_time | split(' ') | last | split ('ms') | first | int }} milliseconds#
{% else %}
Compaction Rate:  [.red]#{{ etcd_time | split(' ') | last | split ('ms') | first | int }} milliseconds#
{% endif %}
****

The following is conducting the fio test (by spinning up a container in the master node, some crazy calculations happening in background, just retrieving the last important lines)  and checks the results provide the 99th percentile of fsync and if it is in the recommended threshold to host etcd or not. 
****
{{ fio_results1 }}


{% if 'the disk can be used to host etcd' in fio_results2 %}
[.green]#{{ fio_results2 }}#
{% else %}
[.red]#{{ fio_results2 }}#
{% endif %}
****

Please review following comprehensive table for health of etcd endpoints, compaction rate for each endpoint and any further error messages regarding etcd. 

[%autowidth]
----
{{ etcd_table }}
----
:sectnums!:

== *References*:

Etcd:
[%autowidth]
----
https://docs.openshift.com/container-platform/4.13/scalability_and_performance/recommended-performance-scale-practices/recommended-etcd-practices.html
https://access.redhat.com/solutions/4885641
----

MachineConfigPools
[%autowidth]
----
1. https://access.redhat.com/solutions/5244121
2. https://docs.openshift.com/container-platform/4.10/rest_api/machine_apis/machineconfigpool-machineconfiguration-openshift-io-v1.html
----

ResourceQuotas
[%autowidth]
----
1. https://docs.openshift.com/container-platform/4.8/applications/quotas/quotas-setting-per-project.html
----

Kubelets 
[%autowidth]
----
1. https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/
2. https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
----

ImageRegistry
[%autowidth]
----
1. https://access.redhat.com/documentation/en-us/openshift_container_platform/4.8/html-single/registry/index
2. https://all.docs.genesys.com/PrivateEdition/Current/PEGuide/OCR
3. https://docs.openshift.com/container-platform/4.8/registry/configuring-registry-operator.html
----